name: Build
on:
  pull_request:
    branches:
    - kisaragi
  push:
    branches:
    - kisaragi
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build
      run: |
        make output.zip
    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/kisaragi' }}
      env:
        NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      run: |
        curl \
        -H "Content-Type: application/zip" \
        -H "Authorization: Bearer $NETLIFY_ACCESS_TOKEN" \
        --data-binary "@output.zip" \
        https://api.netlify.com/api/v1/sites/2e5edfc4-89a3-4851-90fa-f9d4f476a2e2/deploys
